title: MEMH
description: Análises biomecânicas em vídeo
# Temas oficiais do GitHub Pages (fáceis e estáveis)
theme: jekyll-theme-cayman
# Extras úteis
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
